telegram:
  bot:
    username: ${TELEGRAN_BOT_USERMANE:default-username}
    token: ${TELEGRAN_BOT_TOKEN:default-token}
    path: ${TELEGRAN_BOT_PATH:default-path}

logging:
  level:
    org.springframework: ERROR
    com.conversation.manamger.bot: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

cloud:
  platform: ${CLOUD_PLATFORM:local}
  heroku:
    ping-google-cron: 0 0 */6 ? * *

spring:
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false