telegram:
  bot:
    username: ${TELEGRAN_BOT_USERMANE:default-username}
    token: ${TELEGRAN_BOT_TOKEN:default-token}
    path: ${TELEGRAN_BOT_PATH:default-path}

logging:
  level:
    org.springframework: ERROR
    com.conversation.manamger.bot: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

cloud:
  platform: ${CLOUD_PLATFORM:local}
  heroku:
    ping-google-cron: 0 0 */6 ? * *

spring:
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:root}
      roles: admin
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:nimda}